### ISSUE TITLE
npm github-copilot-cli path error

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [yveslaurentcreton/PSGitHubCopilotCLI#1]
First off, great effort! 👍 That said, the script [assumes the path to node modules is in Program Files\nodejs](https://github.com/yveslaurentcreton/PSGitHubCopilotCLI/blob/c1209694d04f93e0caecd47b5c25f8de010f78ab/src/Modules/PSGitHubCopilotCLI/public/Invoke-GitHubCopilotWhatTheShell.ps1#L32)... but the path where npm installs github-copilot-cli on my machine is C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\@githubnext\github-copilot-cli

Attempts to use the script and/or alias results in the error:

```text
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\@githubnext\github-copilot-cli\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.2.0
Apologies! Extracting command failed
```

Perhaps the installation script should verify the path where github-copilot-cli is installed?

**Comment by yveslaurentcreton** [comment]
Now the system checks where the node command is installed and uses that as base for the github copilot cli location.

Please feel free to reopen or log another ticket if you still would experience issues.
Thank you for logging the issue.
